version: '3.8'

services:

  db:
    image: postgres:15
    container_name: helpdesk-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helpdesk_db
    ports:
      - "5433:5432"
    volumes:
      - helpdesk-data:/var/lib/postgresql/data

  api:
    build: ./demo
    container_name: helpdesk-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/helpdesk_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.xml
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  helpdesk-data: